receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  resource:
    attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "otellabs"
      - key: appdynamics.controller.host
        action: upsert
        value: "otellabs.saas.appdynamics.com"
      - key: appdynamics.controller.port
        action: upsert
        value: 443
      # AppD Application name
      - key: service.namespace
        action: upsert
        value: "sagoto_python"
      # AppD Tier name
      - key: service.name
        action: upsert
        value: "Python 3.9"

exporters:
  logging:
    loglevel: debug

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  otlphttp:
    endpoint: "https://pdx-sls-agent-api.saas.appdynamics.com"
    # set X_API_KEY in .env
    headers: {"x-api-key": "${X_API_KEY}"}   

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, jaeger, otlphttp]
      processors: [resource, batch]
    metrics:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
